runtime: java11
env: standard
instance_class: F2
handlers:
  - url: .*
    script: auto
inbound_services:
  - warmup
automatic_scaling:
  max_instances: 10
  min_idle_instances: automatic
  max_idle_instances: 10
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}